name: PunishmentsX
description: An extremely advanced punishments plugin (https://github.com/Cowings/PunishmentsX).
version: ${punishmentsx.desc}
author: Cowings
main: io.github.punishmentsx.PunishmentsX