DATABASE:
  USE: "mongo" #You can use either "mongo" or "mysql"
  MONGO:
    LOCALHOST_NO_AUTH: true #Only use this if you know what it is, this will replace URI if enabled.
    URI: "mongodb://user:pass@127.0.0.1/punishments"
    DB: "punishments"
  MYSQL:
    HOST: "127.0.0.1"
    PORT: 3306
    USER: "user"
    PASSWORD: "password"
    DATABASE: "punishments"
  REDIS:
    ENABLED: true
    HOST: "127.0.0.1"
    PORT: 6379
    CHANNEL: "punishments"

WEBHOOK:
  LINK: ""
  COLOR: 15258703

MESSAGES:
  NO_PERMISSION: "&cNo Permission!"

PERMISSIONS:
  SILENT_VIEW: "punishments.view.silent" #See silent punishments in chat
  HISTORY: "punishments.history" #/history
  PUNISH: "punishments.punish" #/punish
  UNPUNISH: "punishments.unpunish" #/unban, /unmute
  MANUAL: "punishments.manual" #/ban, /mute, /warn, /kick, /tempban, /tempmute

MENUS:
  PUNISH:
    TITLE: "Punishing: %player%"
    SLOTS:
      CHEATING:
        NAME: "&c&lCheats"
        MATERIAL: "DIAMOND_SWORD"
        DEFAULT_REASON: "Cheating"
        PUNISHMENTS:
          - "ban:30d"
          - "ban:90d"
          - "ban:365d"
          - "ban:permanent"
        LORE:
          - " "
          - "&fViolation #1: &e30 day &c(BAN)"
          - "&fViolation #2: &e90 day &c(BAN)"
          - "&fViolation #3: &e365 day &c(BAN)"
          - "&fViolation #4: &ePermanent &c(BAN)"
          - " "
          - "&fPunishments in this category: &e%offenses%"
      SPAMMING:
        NAME: "&c&lSpamming"
        MATERIAL: "PAPER"
        DEFAULT_REASON: "Spamming"
        PUNISHMENTS:
          - "mute:30m"
          - "mute:1d"
          - "mute:7d"
          - "mute:30d"
          - "mute:permanent"
        LORE:
          - " "
          - "&fViolation #1: &e30 minute &c(MUTE)"
          - "&fViolation #2: &e1 day &c(MUTE)"
          - "&fViolation #3: &e7 day &c(MUTE)"
          - "&fViolation #4: &e30 day &c(MUTE)"
          - "&fViolation #5: &ePermanent &c(MUTE)"
          - " "
          - "&fPunishments in this category: &e%offenses%"
          - " "
      FOUL_LANGUAGE:
        NAME: "&c&lFoul Language"
        MATERIAL: "BOOK"
        DEFAULT_REASON: "Foul Language"
        PUNISHMENTS:
          - "mute:1d"
          - "mute:7d"
          - "mute:30d"
          - "mute:90d"
          - "mute:permanent"
        LORE:
          - " "
          - "&fViolation #1: &e1 day &c(MUTE)"
          - "&fViolation #2: &e7 day &c(MUTE)"
          - "&fViolation #3: &e30 day &c(MUTE)"
          - "&fViolation #4: &e90 day &c(MUTE)"
          - "&fViolation #5: &ePermanent &c(MUTE)"
          - " "
          - "&fPunishments in this category: &e%offenses%"
          - " "
      ADVERTISING:
        NAME: "&c&lAdvertising"
        MATERIAL: "GOLD_SWORD"
        DEFAULT_REASON: "Advertising"
        PUNISHMENTS:
          - "mute:30d"
          - "mute:90d"
          - "mute:permanent"
        LORE:
          - " "
          - "&fViolation #1: &e30 day &c(MUTE)"
          - "&fViolation #2: &e90 day &c(MUTE)"
          - "&fViolation #3: &ePermanent &c(MUTE)"
          - " "
          - "&fPunishments in this category: &e%offenses%"

  HISTORY:
    TITLE: "History: %player%"
    ACTIVE_NAME: "&6&l%uuid%"
    INACTIVE_NAME: "&6%uuid%"
    MATERIALS:
      BLACKLIST: "IRON_FENCE"
      BAN: "LADDER"
      MUTE: "ACTIVATOR_RAIL"
      KICK: "VINE"
      WARN: "PAPER"
    PARDONED:
      LORE:
        - "&7&m-----------------------------"
        - "&eTarget: &f%victim%"
        - "&eType: &f%type%"
        - "&eStack: &f%stack%"
        - "&eActive: &f%active%"
        - "&7&m-----------------------------"
        - "&eIssued on: &f%issuedDate%"
        - "&eIssued by: &f%issuer%"
        - "&eReason: &f%issueReason%"
        - "&eExpiry: &f%expiry%"
        - "&7&m-----------------------------"
        - "&ePardoned on: &f%pardonDate%"
        - "&ePardoned by: &f%pardoner%"
        - "&eReason: &f%pardonReason%"
        - "&7&m-----------------------------"
    REGULAR:
      LORE:
        - "&7&m-----------------------------"
        - "&eTarget: &f%victim%"
        - "&eType: &f%type%"
        - "&eStack: &f%stack%"
        - "&eActive: &f%active%"
        - "&7&m-----------------------------"
        - "&eIssued on: &f%issuedDate%"
        - "&eIssued by: &f%issuer%"
        - "&eReason: &f%issueReason%"
        - "&eExpiry: &f%expiry%"
        - "&7&m-----------------------------"
